swagger: '2.0'
info:
  version: '0.1'
  title: Log Cache
  description: 'Simple service that holds stats of unique IP addresses'

host: localhost:5000

schemes:
  - http

basePath: /

produces:
  - application/json

consumes:
  - application/json

paths:
  /status:
    get:
      summary: Get status
      description: 'Returns info about service'
      tags:
        - Health-Check
      responses:
        200:
          description: 'Service info'
          schema:
            $ref: '#/definitions/Health'
  /logs:
    post:
      summary: "Save new log entry record"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "log entry is JSON format"
          required: true
          schema:
            $ref: "#/definitions/LogEntry"
      responses:
        200:
          description: "Ok"
        "401":
          description: "Invalid input"


definitions:
  LogEntry:
    additionalProperties:
      type: string
  Health:
    properties:
      app:
        type: string
        description: app name
      version:
        type: string
        description: app version
      tag:
        type: string
        description: app tag
      build:
        type: string
        description: app build

responses:
  NotFoundError:
    examples:
      bad_body:
        "errcode": 404
        "message": "Not Found"
    description: "Can't found resource"

