api:
  host: 0.0.0.0
  port: 5000
  dev_mode: false
  enable_cors: true
  api_request_timeout: 60


monitoring:
  host: 0.0.0.0
  port: 9102
  dev_mode: false
  enable_cors: false
  api_request_timeout: 60

log:
  app_name: log_cache
  level: env:LOG_LEVEL
  add_trace: true
  sentry: ""
  json: false
