services_init_timeout: 15 # in seconds

api:
  host: 0.0.0.0
  port: 2490
  dev_mode: true
  enable_cors: true
  api_request_timeout: 60

log:
  app_name: log_cache
  level: env:LOG_LEVEL
  add_trace: true
  sentry: ""
  json: false
